export class ApiError extends Error {
  constructor(statusCode, message, errors = null) {
    super(message);
    this.statusCode = statusCode;
    this.status = `${statusCode}`.startsWith("4") ? "fail" : "error";
    this.isOperational = true;
    this.errors = errors;

    Error.captureStackTrace(this, this.constructor);
  }
}

export const handleAsync = (fn) => {
  return async (req, res, next) => {
    try {
      await fn(req, res, next);
    } catch (error) {
      next(error);
    }
  };
};

export const errorHandler = (err, req, res, next) => {
    
  const statusCode = err.statusCode || 500;
  const status = err.status || "error";

  if (process.env.NODE_ENV === "development") {
    res.status(statusCode).json({
      status: status,
      error: err,
      message: err.message,
      statusCode: statusCode,
      stack: err.stack,
    });
  } else {
    if (err.isOperational) {
      res.status(statusCode).json({
        status: status,
        statusCode: statusCode,
        message: err.message,
      });
    } else {
      console.error("ERROR ğŸ’¥", err);
      res.status(500).json({
        status: "error",
        message: "Something went wrong!",
      });
    }
  }
};
